### PR TITLE
Closes #395 Arbitrary start number for ordered list

### LINKED ISSUE #395: Ordered lists and start value
I've noticed a minor bug when creating a list with a start number other than "1". For example, if I type in a comment box:
```
3. hi
4. there
5. github
```
It will change the number and display the saved comment as
```
1. hi
2. there
3. github
```
This also happens if the list is out of order, such as
```
3. hi
9. there
22. github
```
If you attempt to edit the comment, the correct numbers are back where they should be.

### PR DESCRIPTION
**Pull request by gajama**
The CommonMark spec says ordered lists can start with any arbitrary value: <https://spec.commonmark.org/0.29/#start-number> this PR allows that in Markdown Here.

### CODE REVIEW

**Comment by gajama** [comment]
Except the start attribute is deprecated apparently. Which seems weird to me but there you go. I'll try to do this in the CSS instead.

**Comment by gajama** [comment]
Except it's been un-deprecated - because it's not about presentation but has meaning: <https://w3c.github.io/html-reference/ol.html>
So re-opening this!

**Comment by terigee** [comment]
Stop sending me emails, I unsubscribed so leave me alone

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by gajama** [comment]
Unfortunately @terigee you're still listed as subscribed when I look on Github. Maybe try unsubscribing again. I just created the pull request. As far as I know I can't unsubscribe you or make Github not send you emails.

**Comment by sheldhur** [comment]
sdaasd
asfasfas

**Pull request closed without merging**
